package com.rivera.objectfactory.supermarketfactory;

import com.rivera.objectfactory.UI;

public class Main {
    // String dairy; String vegetables; int totalItems; private boolean bill;
    //main method
    //autogenerated tostring

    public static void main(String[] args) {

        System.out.println("Supermarket Shopping List\n\n");

        String dairy = UI.readString("Name of dairy product");
        String vegetables = UI.readString("Name of vegetable\n\n");
        short totalItems = UI.readShort("Total number of items:", (short)1, (short)1000);

        Supermarket generatedSupermarket = new Supermarket(dairy, vegetables, totalItems);

    }

}
