package com.rivera.objectfactory.songfactory;

import com.rivera.objectfactory.UI;

public class Main {
    //Fields: title (String), artist (String), genre (String), seconds (int)
    // main method
    //autogenerated method
    public static void main(String[] args) {  //main method

        System.out.println("Song Factory\n\n");

        String title = UI.readString("What is the title os the song?");
        String artist = UI.readString("What is the artist name?");
        String genre = UI.readString("What genre is the song?");
        int seconds = UI.readInt("How long is the song? (in seconds)", 0, 350);

        Song generatedSong = new Song(title, artist, genre, seconds);

        System.out.println(generatedSong);

    }
}
